server:
  port: 8090

spring:
  application:
    name: consumer-user

eureka:
  instance:
    prefer-ip-address: true # 注册服务的时候使用服务的ip地址
  client:
    register-with-eureka: true # 把自己注册到注册中心
    fetch-registry: true # 从eureka上获取服务的注册信息
    service-url: # 指定注册中心的地址(provider和client会使用)
      defaultZone: http://localhost:8761/eureka # service-url是一个map，defaultZone默认也是这个url