server:
  port: 8761

eureka:
  instance:
    hostname: eureka-server # eureka实例的主机名
  client:
    register-with-eureka: false # 不做高可用的情况下，不需要把自己注册到注册中心
    fetch-registry: false # 不从eureka上获取服务的注册信息(本身作为注册中心，不是消费者client)
    service-url: # 指定注册中心的地址(provider和client会使用)
      defaultZone: http://localhost:8761/eureka # service-url是一个map，defaultZone默认也是这个url
